# Site settings
title: Discuss The Times
email: rhinemainwein@gmail.com
description: "Current Events Blog"
baseurl: ""
url: "http://discussthetimes.com"

# Build settings
markdown: kramdown
permalink: pretty
